name = "Arklib"
lintDriver = "batteries/runLinter"
defaultTargets = ["ArkLib"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longFile = 1500

[moreServerOptions]
linter.mathlibStandardSet = true
linter.style.longFile = 1500

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCV-io"
rev = "2fec6335bbbb18ce0de490f8184af69c8987d705"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.28.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.18.0"

[[require]]
name = "CompPoly"
git = "https://github.com/Verified-zkEVM/CompPoly"
rev = "fe33688378befe303df16c91189df9aff14bb105"

[[lean_lib]]
name = "ArkLib"
