name = "Arklib"
lintDriver = "batteries/runLinter"
defaultTargets = ["ArkLib"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.longFile = 1500

[moreServerOptions]
linter.mathlibStandardSet = true
linter.style.longFile = 1500

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCV-io"
rev = "88b4fe7b9c66dc40f083d67d50aa67338fd578f8"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "v4.29.0"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"
rev = "lean4.18.0"

[[require]]
name = "CompPoly"
git = "https://github.com/Verified-zkEVM/CompPoly"
rev = "56d10c947e3427c852b708a424f585c5673b039c"

[[lean_lib]]
name = "ArkLib"
